site_name: Cocopot
pages:
- Home: index.md
- Install: install.md
- Quick Start: quickstart.md
- Advanced: advanced.md
- SlackUserGuide: for_flask_user.md
- API Documents:
    - Application: api_app.md
    - Blueprints: api_blueprints.md
    - Request: api_request.md
    - Response: api_response.md
    - DataStructure: api_datastructures.md
    - Routing: api_routing.md
theme: readthedocs
